### ISSUE TITLE
This library is incorrectly bundled on npm

### ISSUE THREAD

**Issue by AdrianoRuberto** [uiwjs/react-codepen#43]
Hello,

I'm trying to use this library with `vitejs` and it seems that this library isn't correctly bundled.

The error I have:

> [common-js--resolver] Failed to resolve entry for package "@uiw/react-codepen". The package may have incorrect main/module/exports specified in its package.json

The package.json have `"module": "esm/index.js"` but it doesn't exists  in the `node_modules`
![image](https://user-images.githubusercontent.com/17402643/227582817-c6e13608-4b3a-4814-b7c9-5a43b611e9db.png)

**Comment by jaywcjlove** [comment]
@AdrianoRuberto Thx!

![image](https://user-images.githubusercontent.com/1680273/227678409-c3d2c927-ac83-4d1b-9af4-de05eb359787.png)
